spring:
  datasource:
    dynamic:
      primary: study
      datasource:
        study:
#          url: jdbc:p6spy:mysql://116.62.165.204:3306/study?useUnicode=false&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          username: root
          password: cq520221
          url: jdbc:mysql://116.62.165.204:3306/study?useUnicode=false&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #上传文件总的最大值
  servlet:
    multipart:
      #      最大请求大小
      max-request-size: 300MB
      #      最大文件大小
      max-file-size: 300MB
      #      开启mutipart上传功能
      enabled: true
  http:
    encoding:
      charset: utf-8
      enabled: true
  application:
    name: ware-fast-dfs

  redis:
    host: 116.62.165.204
    port: 6379
    jedis:
      pool:
        max-wait: 30000 #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-active: 100 #连接池最大连接数(使用负值表示没有限制)
        max-idle: 20 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000  #连接超时
    database: 0
    password: 123456
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/*.xml


fdfs:
  #链接超时
  connect-timeout: 6000
  #  #读取时间
  so-timeout: 15000
  thumb-image:
    width: 150
    height: 150
  tracker-list: 116.62.165.204:22122



#  perUrl: https://116.62.165.204/
#









